Global:
  AmountOfSpawnerEggsYouNeed: 5
  perMobPermissions: true
Messages:
  ChangeSpawner: '&2Spawnertype changed to %entity.'
  NotEnoughSpawnerEggs: '&cYou dont have enough %entity Eggs.'
  FailedSpawnerEggs: '&cFailed changing the spawner type!'
