name: MobSpawnerEggChanger
main: me.p000ison.MobSpawnerEggChanger.MobSpawnerEggChanger
version: 1.3
author: p000ison
permissions:
    sec.spawnerchange:
        description: Allows you to change MobSpawner Type.
        default: op